version: '3'

services:
  map:
    image: mstr6789/india:1.0.0
    volumes:
      - ${pwd}/openstreetmap-data:/var/lib/postgresql/12/main
      - ${pwd}/openstreetmap-rendered-tiles:/var/lib/mod_tile
    ports:
      - "8888:80"
    command: "run"

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:
    external: true
